language: elixir
elixir:
  - 1.3.2
  - 1.3.1
  - 1.3.0
otp_release:
  - 19.0
  - 18.3
  - 18.2
  - 18.1
  - 18.0
  - 17.5
sudo: false
script:
- "MIX_ENV=test mix do deps.get, test && mix compile && MIX_ENV=test mix coveralls.travis"